upstream backend_pool {
    server backend:5050;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /record {
        proxy_pass http://backend_pool;
        proxy_set_header Host $host;
    }

    location /health {
        proxy_pass http://backend_pool;
    }

    location /metrics {
        proxy_pass http://backend_pool;
    }
}
